### ISSUE TITLE
Panic when using `ROUND` function with big numbers

### ISSUE THREAD

**Issue by frannoriega** [readysettech/readyset#289]
When running `SELECT ROUND(3.4028235000000000000000000000000000000, 2147483647);` on ReadySet, the application panics with the following error:

```
called `Result::unwrap()` on an `Err` value: DfValueConversionError { src_type: "f64", target_type: "DfValue", details: "" }
thread 'example_exprs_eval_same_as_postgres' panicked at 'called `Result::unwrap()` on an `Err` value: DfValueConversionError { src_type: "f64", target_type: "DfValue", details: "" }', /Users/francisconoriega/Workspace/readyset/1/public/dataflow-expression/src/eval/builtins.rs:492:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f63ccaf25f74151a5d8ce057904cd944074b01d2/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/f63ccaf25f74151a5d8ce057904cd944074b01d2/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/f63ccaf25f74151a5d8ce057904cd944074b01d2/library/core/src/result.rs:1750:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f63ccaf25f74151a5d8ce057904cd944074b01d2/library/core/src/result.rs:1090:23
   4: dataflow_expression::eval::builtins::<impl dataflow_expression::BuiltinFunction>::eval
             at ./src/eval/builtins.rs:492:48
   5: dataflow_expression::eval::<impl dataflow_expression::Expr>::eval
             at ./src/eval.rs:286:40
   6: postgres_oracle::common::parse_lower_eval
             at ./tests/common/mod.rs:35:11
   7: postgres_oracle::compare_eval::{{closure}}
             at ./tests/postgres_oracle.rs:33:22
   8: postgres_oracle::example_exprs_eval_same_as_postgres::{{closure}}
             at ./tests/postgres_oracle.rs:106:36
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f63ccaf25f74151a5d8ce057904cd944074b01d2/library/core/src/future/future.rs:125:9
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f63ccaf25f74151a5d8ce057904cd944074b01d2/library/core/src/future/future.rs:125:9
  11: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/scheduler/current_thread.rs:541:57
  12: tokio::runtime::coop::with_budget
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/coop.rs:107:5
  13: tokio::runtime::coop::budget
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/coop.rs:73:5
  14: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/scheduler/current_thread.rs:541:25
  15: tokio::runtime::scheduler::current_thread::Context::enter
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/scheduler/current_thread.rs:350:19
  16: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/scheduler/current_thread.rs:540:36
  17: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/scheduler/current_thread.rs:615:57
  18: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/macros/scoped_tls.rs:61:9
  19: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/scheduler/current_thread.rs:615:27
  20: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/scheduler/current_thread.rs:530:19
  21: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/scheduler/current_thread.rs:154:24
  22: tokio::runtime::runtime::Runtime::block_on
             at /Users/francisconoriega/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/runtime.rs:302:47
  23: postgres_oracle::example_exprs_eval_same_as_postgres
             at ./tests/postgres_oracle.rs:68:5
  24: postgres_oracle::example_exprs_eval_same_as_postgres::{{closure}}
             at ./tests/postgres_oracle.rs:46:48
  25: core::ops::function::FnOnce::call_once
             at /rustc/f63ccaf25f74151a5d8ce057904cd944074b01d2/library/core/src/ops/function.rs:250:5
  26: core::ops::function::FnOnce::call_once
             at /rustc/f63ccaf25f74151a5d8ce057904cd944074b01d2/library/core/src/ops/function.rs:250:5
```

Running the same query in PostgreSQL returns a correct value

## Steps to reproduce

1. Go to `dataflow-expression/tests/postgres_oracle.rs` file.
2. Find the `example_exprs_eval_same_as_postgres` test.
3. Add `round(3.4028235000000000000000000000000000000, 2147483647)` to the list of expressions being tested.
4. Run the test.

### Additional notes

This problem occurs because of the calculations we perform in order to calculate the `round` value with the given precision.

In that process, we multiply and then divide, and it seems like the multiplication step, since it involves big numbers, ends up yielding `infinity`, which then fails the conversion.

As a palliative for this, the `round` macro (where the calculations are performed) should not use any `unwrap`s, and use `?` instead (since the function already returns a `Result`, this is a very straightforward fix). This won't fix the incorrect results (an error on our side), but it will prevent the application from panicking.

**Comment by frannoriega** [comment]
High priority to remove the panic, but not necessarily to fully implement REA-1933

**Comment by frannoriega** [comment]
This may be related to [https://linear.app/readyset/issue/REA-1933/support-postgres-numeric-with-full-allowed-precision](https://linear.app/readyset/issue/REA-1933/support-postgres-numeric-with-full-allowed-precision)

**Comment by lukoktonos** [comment]
Related: [REA-4249](https://linear.app/readyset/issue/REA-4249/postgres-correctness-testing)
